import { useState } from "react";
import type { Leg, Stop, TransportMode } from "../../domain/models";
import type { LegDraft } from "../../hooks/useItinerary";
const modes: TransportMode[] = ["walk", "bike", "bus", "metro", "taxi", "drive", "train", "highSpeedRail", "flight", "ferry", "other"];
interface LegEditorProps { leg?: Leg; stops: Stop[]; currency: string; onSave: (draft: LegDraft) => Promise<void>; onClose: () => void; }
export function LegEditor({ leg, stops, currency, onSave, onClose }: LegEditorProps) {
  const [draft, setDraft] = useState<LegDraft>({ fromStopId: leg?.fromStopId ?? stops[0]?.id ?? "", toStopId: leg?.toStopId ?? stops[1]?.id ?? "", mode: leg?.mode ?? "train", departsAt: leg?.departsAt ?? "", arrivesAt: leg?.arrivesAt ?? "", serviceNumber: leg?.serviceNumber ?? "", notes: leg?.notes ?? "" }); const [error, setError] = useState(""); const [expense, setExpense] = useState("");
  return <div className="dialog-overlay" role="dialog" aria-modal="true" aria-label="编辑交通"><form className="dialog-panel dialog-form" onSubmit={async (event) => { event.preventDefault(); try { await onSave(draft); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : "保存失败"); } }}><div className="dialog-header"><h2 className="dialog-title">{leg ? "编辑交通" : "添加交通"}</h2></div>
    <label className="dialog-field">出发节点<select className="dialog-input" value={draft.fromStopId} onChange={(e) => setDraft({ ...draft, fromStopId: e.target.value })}>{stops.map((stop) => <option key={stop.id} value={stop.id}>{stop.title}</option>)}</select></label>
    <label className="dialog-field">到达节点<select className="dialog-input" value={draft.toStopId} onChange={(e) => setDraft({ ...draft, toStopId: e.target.value })}>{stops.map((stop) => <option key={stop.id} value={stop.id}>{stop.title}</option>)}</select></label>
    <label className="dialog-field">方式<select className="dialog-input" value={draft.mode} onChange={(e) => setDraft({ ...draft, mode: e.target.value as TransportMode })}>{modes.map((mode) => <option key={mode}>{mode}</option>)}</select></label><label className="dialog-field">班次<input className="dialog-input" value={draft.serviceNumber} onChange={(e) => setDraft({ ...draft, serviceNumber: e.target.value })} /></label>
    <label className="dialog-field">出发时间<input className="dialog-input" type="datetime-local" value={draft.departsAt} onChange={(e) => setDraft({ ...draft, departsAt: e.target.value })} /></label><label className="dialog-field">到达时间<input className="dialog-input" type="datetime-local" value={draft.arrivesAt} onChange={(e) => setDraft({ ...draft, arrivesAt: e.target.value })} /></label><label className="dialog-field">备注<textarea className="dialog-input dialog-textarea" value={draft.notes} onChange={(e) => setDraft({ ...draft, notes: e.target.value })} /></label>{!leg?.expenseId && <label className="dialog-field">同时添加预计交通费（{currency}）<input className="dialog-input" inputMode="decimal" value={expense} onChange={(e) => { setExpense(e.target.value); setDraft((current) => ({ ...current, expenseAmountMinor: e.target.value ? Math.round(Number(e.target.value) * (currency === "JPY" ? 1 : 100)) : undefined, expenseCurrency: currency })); }} /></label>}{error && <p className="dialog-error">{error}</p>}<div className="dialog-actions"><button type="button" className="dialog-btn-cancel" onClick={onClose}>取消</button><button className="dialog-btn-submit" disabled={stops.length < 2}>保存</button></div>
  </form></div>;
}
